create table if not exists public.guide_leads (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 254),
  phone text not null check (char_length(phone) between 7 and 30),
  guide text not null default 'smart-womans-personal-safety-guide',
  created_at timestamptz not null default now()
);

alter table public.guide_leads enable row level security;

create policy "Allow public guide lead submissions"
on public.guide_leads
for insert
to anon
with check (
  char_length(name) between 1 and 100
  and char_length(email) between 3 and 254
  and char_length(phone) between 7 and 30
);

revoke all on table public.guide_leads from anon;
grant insert on table public.guide_leads to anon;
grant usage, select on sequence public.guide_leads_id_seq to anon;
